name: common
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  flutter_svg: ^2.2.3
  lottie: ^3.3.2
  equatable: ^2.0.8
  envied: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  build_runner: ^2.10.4
  envied_generator: ^1.3.2
  json_serializable: ^6.11.3
  flutter_gen_runner: ^5.12.0

flutter_gen:
  output: lib/src/asset/
  integrations:
    lottie: true
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  assets:
    - assets/color/
    - assets/lottie/
    - assets/icons/
    - assets/images/